package Initialization;

import java.util.*;
import javax.persistence.*;
import Schema.*;

public class Initialization implements Inserts, Links{
	public static void main(String[] args) {
		java.util.Map<Object,Object> map = new java.util.HashMap<Object,Object>();
		map.put("openjpa.ConnectionUserName", "root");
		map.put("openjpa.ConnectionPassword", "");
		map.put("openjpa.ConnectionURL", "jdbc:mysql://127.0.0.1/FIFA2014");
		map.put("openjpa.ConnectionDriverName", "com.mysql.jdbc.Driver");
		map.put("openjpa.jdbc.SynchronizeMappings", "buildSchema");
		
	    EntityManagerFactory factory = Persistence.createEntityManagerFactory("FIFA2014", map);
	    EntityManager em = factory.createEntityManager();
	    
	    List<Object> InstanceList = new ArrayList<Object>();
	    
	    Admin admin = Inserts.InsertAdmin(InstanceList, "admin", "0000");
	    SecAdmin secadmin =Inserts.InsertSecAdmin(InstanceList, "secadmin", "0000");
	    
	    Team Germany = Inserts.InsertTeam(InstanceList, "Germany", "LOEW Joachim", 7, 6, 1, 0, 1);
	    Player ManuelNEUER = Inserts.InsertPlayer(InstanceList, "Manuel NEUER", 1, 28);
	    Links.LinkTeamAndPlayer(Germany, ManuelNEUER);
	    Player KevinGROßKREUTZ = Inserts.InsertPlayer(InstanceList, "Kevin GROßKREUTZ", 2, 26);
	    Links.LinkTeamAndPlayer(Germany, KevinGROßKREUTZ);
	    Player MatthiasGINTER = Inserts.InsertPlayer(InstanceList, "Matthias GINTER", 3, 20);
	    Links.LinkTeamAndPlayer(Germany, MatthiasGINTER);
	    Player BenediktHOEWEDES = Inserts.InsertPlayer(InstanceList, "Benedikt HOEWEDES", 4, 26);
	    Links.LinkTeamAndPlayer(Germany, BenediktHOEWEDES);
	    Player MatsHUMMELS = Inserts.InsertPlayer(InstanceList, "Mats HUMMELS", 5, 26);
	    Links.LinkTeamAndPlayer(Germany, MatsHUMMELS);
	    Player SamiKHEDIRA = Inserts.InsertPlayer(InstanceList, "Sami KHEDIRA", 6, 27);
	    Links.LinkTeamAndPlayer(Germany, SamiKHEDIRA);
	    Player BastianSCHWEINSTEIGER = Inserts.InsertPlayer(InstanceList, "Bastian SCHWEINSTEIGER", 7, 30);
	    Links.LinkTeamAndPlayer(Germany, BastianSCHWEINSTEIGER);
	    Player MesutOEZIL = Inserts.InsertPlayer(InstanceList, "Mesut OEZIL", 8, 26);
	    Links.LinkTeamAndPlayer(Germany, MesutOEZIL);
	    Player AndreSCHUERRLE = Inserts.InsertPlayer(InstanceList, "Andre SCHUERRLE", 9, 24);
	    Links.LinkTeamAndPlayer(Germany, AndreSCHUERRLE);
	    Player LukasPODOLSKI = Inserts.InsertPlayer(InstanceList, "Lukas PODOLSKI", 10, 29);
	    Links.LinkTeamAndPlayer(Germany, LukasPODOLSKI);
	    Player MiroslavKLOSE = Inserts.InsertPlayer(InstanceList, "Miroslav KLOSE", 11, 36);
	    Links.LinkTeamAndPlayer(Germany, MiroslavKLOSE);
	    Player RonRobertZIELER = Inserts.InsertPlayer(InstanceList, "Ron-Robert ZIELER", 12, 25);
	    Links.LinkTeamAndPlayer(Germany, RonRobertZIELER);
	    Player ThomasMUELLER = Inserts.InsertPlayer(InstanceList, "Thomas MUELLER", 13, 25);
	    Links.LinkTeamAndPlayer(Germany, ThomasMUELLER);
	    Player JulianDRAXLER = Inserts.InsertPlayer(InstanceList, "Julian DRAXLER", 14, 21);
	    Links.LinkTeamAndPlayer(Germany, JulianDRAXLER);
	    Player ErikDURM = Inserts.InsertPlayer(InstanceList, "Erik DURM", 15, 22);
	    Links.LinkTeamAndPlayer(Germany, ErikDURM);
	    Player PhilippLAHM = Inserts.InsertPlayer(InstanceList, "Philipp LAHM", 16, 31);
	    Links.LinkTeamAndPlayer(Germany, PhilippLAHM);
	    Player PerMERTESACKER = Inserts.InsertPlayer(InstanceList, "Per MERTESACKER", 17, 30);
	    Links.LinkTeamAndPlayer(Germany, PerMERTESACKER);
	    Player ToniKROOS = Inserts.InsertPlayer(InstanceList, "Toni KROOS", 18, 24);
	    Links.LinkTeamAndPlayer(Germany, ToniKROOS);
	    Player MarioGOETZE = Inserts.InsertPlayer(InstanceList, "Mario GOETZE", 19, 22);
	    Links.LinkTeamAndPlayer(Germany, MarioGOETZE);
	    Player JeromeBOATENG = Inserts.InsertPlayer(InstanceList, "Jerome BOATENG", 20, 26);
	    Links.LinkTeamAndPlayer(Germany, JeromeBOATENG);
	    Player ShkodranMUSTAFI = Inserts.InsertPlayer(InstanceList, "Shkodran MUSTAFI",21, 22);
	    Links.LinkTeamAndPlayer(Germany, ShkodranMUSTAFI);
	    Player RomanWEIDENFELLER = Inserts.InsertPlayer(InstanceList, "Roman WEIDENFELLER", 22, 34);
	    Links.LinkTeamAndPlayer(Germany, RomanWEIDENFELLER);
	    Player ChristophKRAMER = Inserts.InsertPlayer(InstanceList, "Christoph KRAMER", 23, 23);
	    Links.LinkTeamAndPlayer(Germany, ChristophKRAMER);

	    Team Argentina = Inserts.InsertTeam(InstanceList, "Argentina", "SABELLA Alejandro", 9, 6, 0, 1, 2);
	    Player SergioROMERO = Inserts.InsertPlayer(InstanceList, "Sergio ROMERO", 1, 27);
	    Links.LinkTeamAndPlayer(Argentina, SergioROMERO);
	    Player EzequielGARAY = Inserts.InsertPlayer(InstanceList, "Ezequiel GARAY", 2, 28);
	    Links.LinkTeamAndPlayer(Argentina, EzequielGARAY);
	    Player HugoCAMPAGNARO = Inserts.InsertPlayer(InstanceList, "Hugo CAMPAGNARO", 3, 34);
	    Links.LinkTeamAndPlayer(Argentina, HugoCAMPAGNARO);
	    Player PabloZABALETA = Inserts.InsertPlayer(InstanceList, "Pablo ZABALETA", 4, 29);
	    Links.LinkTeamAndPlayer(Argentina, PabloZABALETA);
	    Player FernandoGAGO = Inserts.InsertPlayer(InstanceList, "Fernando GAGO", 5, 28);
	    Links.LinkTeamAndPlayer(Argentina, FernandoGAGO);
	    Player LucasBIGLIA = Inserts.InsertPlayer(InstanceList, "Lucas BIGLIA", 6, 28);
	    Links.LinkTeamAndPlayer(Argentina, LucasBIGLIA);
	    Player AngelDIMARIA = Inserts.InsertPlayer(InstanceList, "Angel DI MARIA", 7, 26);
	    Links.LinkTeamAndPlayer(Argentina, AngelDIMARIA);
	    Player EnzoPEREZ = Inserts.InsertPlayer(InstanceList, "Enzo PEREZ", 8, 28);
	    Links.LinkTeamAndPlayer(Argentina, EnzoPEREZ);
	    Player GonzaloHIGUAIN = Inserts.InsertPlayer(InstanceList, "Gonzalo HIGUAIN", 9, 27);
	    Links.LinkTeamAndPlayer(Argentina, GonzaloHIGUAIN);
	    Player LionelMESSI = Inserts.InsertPlayer(InstanceList, "Lionel MESSI", 10, 27);
	    Links.LinkTeamAndPlayer(Argentina, LionelMESSI);
	    Player MaxiRODRIGUEZ = Inserts.InsertPlayer(InstanceList, "Maxi RODRIGUEZ", 11, 33);
	    Links.LinkTeamAndPlayer(Argentina, MaxiRODRIGUEZ);
	    Player AgustínORIÓN = Inserts.InsertPlayer(InstanceList, "Agustín ORIÓN", 12, 33);
	    Links.LinkTeamAndPlayer(Argentina, AgustínORIÓN);
	    Player AugustoFERNÁNDEZ = Inserts.InsertPlayer(InstanceList, "Augusto FERNÁNDEZ", 13, 28);
	    Links.LinkTeamAndPlayer(Argentina, AugustoFERNÁNDEZ);
	    Player JavierMASCHERANO = Inserts.InsertPlayer(InstanceList, "Javier MASCHERANO", 14, 30);
	    Links.LinkTeamAndPlayer(Argentina, JavierMASCHERANO);
	    Player MartínDEMICHELIS = Inserts.InsertPlayer(InstanceList, "Martín DEMICHELIS", 15, 34);
	    Links.LinkTeamAndPlayer(Argentina, MartínDEMICHELIS);
	    Player MarcosROJO = Inserts.InsertPlayer(InstanceList, "Marcos ROJO", 16, 25);
	    Links.LinkTeamAndPlayer(Argentina, MarcosROJO);
	    Player FedericoFERNANDEZ = Inserts.InsertPlayer(InstanceList, "Federico FERNANDEZ", 17, 25);
	    Links.LinkTeamAndPlayer(Argentina, FedericoFERNANDEZ);
	    Player RodrigoPALACIO = Inserts.InsertPlayer(InstanceList, "Rodrigo PALACIO", 18, 32);
	    Links.LinkTeamAndPlayer(Argentina, RodrigoPALACIO);
	    Player RicardoALVAREZ = Inserts.InsertPlayer(InstanceList, "Ricardo ALVAREZ", 19, 26);
	    Links.LinkTeamAndPlayer(Argentina, RicardoALVAREZ);
	    Player SergioAGUERO = Inserts.InsertPlayer(InstanceList, "Sergio AGUERO", 20, 26);
	    Links.LinkTeamAndPlayer(Argentina, SergioAGUERO);
	    Player MarianoANDUJAR = Inserts.InsertPlayer(InstanceList, "Mariano ANDUJAR",21, 31);
	    Links.LinkTeamAndPlayer(Argentina, MarianoANDUJAR);
	    Player EzequielLAVEZZI = Inserts.InsertPlayer(InstanceList, "Ezequiel LAVEZZI", 22, 29);
	    Links.LinkTeamAndPlayer(Argentina, EzequielLAVEZZI);
	    Player JoséBASANTA = Inserts.InsertPlayer(InstanceList, "José BASANTA", 23, 30);
	    Links.LinkTeamAndPlayer(Argentina, JoséBASANTA);

	    Team Netherlands = Inserts.InsertTeam(InstanceList, "Netherlands", "Louis VAN GAAL", 9, 5, 0, 2, 3);
	    Player JasperCILLESSEN = Inserts.InsertPlayer(InstanceList, "Jasper CILLESSEN", 1, 25);
	    Links.LinkTeamAndPlayer(Netherlands, JasperCILLESSEN);
	    Player RonVLAAR = Inserts.InsertPlayer(InstanceList, "Ron VLAAR", 2, 29);
	    Links.LinkTeamAndPlayer(Netherlands, RonVLAAR);
	    Player StefanDEVRIJ = Inserts.InsertPlayer(InstanceList, "Stefan DE VRIJ", 3, 22);
	    Links.LinkTeamAndPlayer(Netherlands, StefanDEVRIJ);
	    Player BrunoMARTINSINDI = Inserts.InsertPlayer(InstanceList, "Bruno MARTINS INDI", 4, 22);
	    Links.LinkTeamAndPlayer(Netherlands, BrunoMARTINSINDI);
	    Player DaleyBLIND = Inserts.InsertPlayer(InstanceList, "Daley BLIND", 5, 24);
	    Links.LinkTeamAndPlayer(Netherlands, DaleyBLIND);
	    Player NigelDEJONG = Inserts.InsertPlayer(InstanceList, "Nigel DE JONG", 6, 30);
	    Links.LinkTeamAndPlayer(Netherlands, NigelDEJONG);
	    Player DarylJANMAAT = Inserts.InsertPlayer(InstanceList, "Daryl JANMAAT", 7, 25);
	    Links.LinkTeamAndPlayer(Netherlands, DarylJANMAAT);
	    Player JonathanDEGUZMAN = Inserts.InsertPlayer(InstanceList, "Jonathan DE GUZMAN", 8, 25);
	    Links.LinkTeamAndPlayer(Netherlands, JonathanDEGUZMAN);
	    Player RobinVANPERSIE = Inserts.InsertPlayer(InstanceList, "Robin VAN PERSIE", 9, 31);
	    Links.LinkTeamAndPlayer(Netherlands, RobinVANPERSIE);
	    Player WesleySNEIJDER = Inserts.InsertPlayer(InstanceList, "Wesley SNEIJDER", 10, 30);
	    Links.LinkTeamAndPlayer(Netherlands, WesleySNEIJDER);
	    Player ArjenROBBEN = Inserts.InsertPlayer(InstanceList, "Arjen ROBBEN", 11, 30);
	    Links.LinkTeamAndPlayer(Netherlands, ArjenROBBEN);
	    Player PaulVERHAEGH = Inserts.InsertPlayer(InstanceList, "Paul VERHAEGH", 12, 31);
	    Links.LinkTeamAndPlayer(Netherlands, PaulVERHAEGH);
	    Player JoelVELTMAN = Inserts.InsertPlayer(InstanceList, "Joel VELTMAN", 13, 22);
	    Links.LinkTeamAndPlayer(Netherlands, JoelVELTMAN);
	    Player TerenceKONGOLO = Inserts.InsertPlayer(InstanceList, "Terence KONGOLO", 14, 20);
	    Links.LinkTeamAndPlayer(Netherlands, TerenceKONGOLO);
	    Player DirkKUYT = Inserts.InsertPlayer(InstanceList, "Dirk KUYT", 15, 34);
	    Links.LinkTeamAndPlayer(Netherlands, DirkKUYT);
	    Player JordyCLASIE = Inserts.InsertPlayer(InstanceList, "Jordy CLASIE", 16, 23);
	    Links.LinkTeamAndPlayer(Netherlands, JordyCLASIE);
	    Player JeremainLENS = Inserts.InsertPlayer(InstanceList, "Jeremain LENS", 17, 27);
	    Links.LinkTeamAndPlayer(Netherlands, JeremainLENS);
	    Player LeroyFER = Inserts.InsertPlayer(InstanceList, "Leroy FER", 18, 24);
	    Links.LinkTeamAndPlayer(Netherlands, LeroyFER);
	    Player KlaasJanHUNTELAAR = Inserts.InsertPlayer(InstanceList, "Klaas Jan HUNTELAAR", 19, 31);
	    Links.LinkTeamAndPlayer(Netherlands, KlaasJanHUNTELAAR);
	    Player GeorginioWijnaldum = Inserts.InsertPlayer(InstanceList, "Georginio Wijnaldum", 20, 24);
	    Links.LinkTeamAndPlayer(Netherlands, GeorginioWijnaldum);
	    Player MemphisDEPAY = Inserts.InsertPlayer(InstanceList, "Memphis DEPAY",21, 20);
	    Links.LinkTeamAndPlayer(Netherlands, MemphisDEPAY);
	    Player MichelVORM = Inserts.InsertPlayer(InstanceList, "Michel VORM", 22, 31);
	    Links.LinkTeamAndPlayer(Netherlands, MichelVORM);
	    Player TimKRUL = Inserts.InsertPlayer(InstanceList, "Tim KRUL", 23, 26);
	    Links.LinkTeamAndPlayer(Netherlands, TimKRUL);

	    Team Brazil = Inserts.InsertTeam(InstanceList, "Brazil", "SCOLARI Luiz Felipe", 7, 4, 1, 2, 4);
	    Player JEFFERSON = Inserts.InsertPlayer(InstanceList, "JEFFERSON", 1, 31);
	    Links.LinkTeamAndPlayer(Brazil, JEFFERSON);
	    Player DANIALVES = Inserts.InsertPlayer(InstanceList, "DANI ALVES", 2, 31);
	    Links.LinkTeamAndPlayer(Brazil, DANIALVES);
	    Player THIAGOSILVA = Inserts.InsertPlayer(InstanceList, "THIAGO SILVA", 3, 30);
	    Links.LinkTeamAndPlayer(Brazil, THIAGOSILVA);
	    Player DAVIDLUIZ = Inserts.InsertPlayer(InstanceList, "DAVID LUIZ", 4, 27);
	    Links.LinkTeamAndPlayer(Brazil, DAVIDLUIZ);
	    Player FERNANDINHO = Inserts.InsertPlayer(InstanceList, "FERNANDINHO", 5, 29);
	    Links.LinkTeamAndPlayer(Brazil, FERNANDINHO);
	    Player MARCELO = Inserts.InsertPlayer(InstanceList, "MARCELO", 6, 26);
	    Links.LinkTeamAndPlayer(Brazil, MARCELO);
	    Player HULK = Inserts.InsertPlayer(InstanceList, "HULK", 7, 28);
	    Links.LinkTeamAndPlayer(Brazil, HULK);
	    Player PAULINHO = Inserts.InsertPlayer(InstanceList, "PAULINHO", 8, 26);
	    Links.LinkTeamAndPlayer(Brazil, PAULINHO);
	    Player FRED = Inserts.InsertPlayer(InstanceList, "FRED", 9, 31);
	    Links.LinkTeamAndPlayer(Brazil, FRED);
	    Player NEYMAR = Inserts.InsertPlayer(InstanceList, "NEYMAR", 10, 22);
	    Links.LinkTeamAndPlayer(Brazil, NEYMAR);
	    Player OSCAR = Inserts.InsertPlayer(InstanceList, "OSCAR", 11, 23);
	    Links.LinkTeamAndPlayer(Brazil, OSCAR);
	    Player JULIOCESAR = Inserts.InsertPlayer(InstanceList, "JULIO CESAR", 12, 35);
	    Links.LinkTeamAndPlayer(Brazil, JULIOCESAR);
	    Player DANTE = Inserts.InsertPlayer(InstanceList, "DANTE", 13, 31);
	    Links.LinkTeamAndPlayer(Brazil, DANTE);
	    Player MAXWELL = Inserts.InsertPlayer(InstanceList, "MAXWELL", 14, 34);
	    Links.LinkTeamAndPlayer(Brazil, MAXWELL);
	    Player HENRIQUE = Inserts.InsertPlayer(InstanceList, "HENRIQUE", 15, 28);
	    Links.LinkTeamAndPlayer(Brazil, HENRIQUE);
	    Player RAMIRES = Inserts.InsertPlayer(InstanceList, "RAMIRES", 16, 27);
	    Links.LinkTeamAndPlayer(Brazil, RAMIRES);
	    Player LuizGUSTAVO = Inserts.InsertPlayer(InstanceList, "Luiz GUSTAVO", 17, 27);
	    Links.LinkTeamAndPlayer(Brazil, LuizGUSTAVO);
	    Player HERNANES = Inserts.InsertPlayer(InstanceList, "HERNANES", 18, 29);
	    Links.LinkTeamAndPlayer(Brazil, HERNANES);
	    Player WILLIAN = Inserts.InsertPlayer(InstanceList, "WILLIAN", 19, 26);
	    Links.LinkTeamAndPlayer(Brazil, WILLIAN);
	    Player BERNARD = Inserts.InsertPlayer(InstanceList, "BERNARD", 20, 22);
	    Links.LinkTeamAndPlayer(Brazil, BERNARD);
	    Player Jô = Inserts.InsertPlayer(InstanceList, "Jô",21, 27);
	    Links.LinkTeamAndPlayer(Brazil, Jô);
	    Player VICTOR = Inserts.InsertPlayer(InstanceList, "VICTOR", 22, 31);
	    Links.LinkTeamAndPlayer(Brazil, VICTOR);
	    Player MAICON = Inserts.InsertPlayer(InstanceList, "MAICONL", 23, 33);
	    Links.LinkTeamAndPlayer(Brazil, MAICON);

	    Team Colombia = Inserts.InsertTeam(InstanceList, "Colombia", "José PEKERMAN", 9, 4, 0, 1, 5);
	    Player DavidOSPINA = Inserts.InsertPlayer(InstanceList, "David OSPINA", 1, 26);
	    Links.LinkTeamAndPlayer(Colombia, DavidOSPINA);
	    Player CristianZAPATA = Inserts.InsertPlayer(InstanceList, "Cristian ZAPATA", 2, 28);
	    Links.LinkTeamAndPlayer(Colombia, CristianZAPATA);
	    Player MarioYEPES = Inserts.InsertPlayer(InstanceList, "Mario YEPES", 3, 38);
	    Links.LinkTeamAndPlayer(Colombia, MarioYEPES);
	    Player SantiagoArias = Inserts.InsertPlayer(InstanceList, "Santiago Arias", 4, 22);
	    Links.LinkTeamAndPlayer(Colombia, SantiagoArias);
	    Player CarlosCARBONERO = Inserts.InsertPlayer(InstanceList, "Carlos CARBONERO", 5, 24);
	    Links.LinkTeamAndPlayer(Colombia, CarlosCARBONERO);
	    Player CarlosSANCHEZ = Inserts.InsertPlayer(InstanceList, "Carlos SANCHEZ", 6, 28);
	    Links.LinkTeamAndPlayer(Colombia, CarlosSANCHEZ);
	    Player PabloARMERO = Inserts.InsertPlayer(InstanceList, "Pablo ARMERO", 7, 28);
	    Links.LinkTeamAndPlayer(Colombia, PabloARMERO);
	    Player AbelAGUILAR = Inserts.InsertPlayer(InstanceList, "Abel AGUILAR", 8, 29);
	    Links.LinkTeamAndPlayer(Colombia, AbelAGUILAR);
	    Player TeofiloGUTIERREZ = Inserts.InsertPlayer(InstanceList, "Teofilo GUTIERREZ", 9, 29);
	    Links.LinkTeamAndPlayer(Colombia, TeofiloGUTIERREZ);
	    Player JamesRODRIGUEZ = Inserts.InsertPlayer(InstanceList, "James RODRIGUEZ", 10, 23);
	    Links.LinkTeamAndPlayer(Colombia, JamesRODRIGUEZ);
	    Player JuanCUADRADO = Inserts.InsertPlayer(InstanceList, "Juan CUADRADO", 11, 26);
	    Links.LinkTeamAndPlayer(Colombia, JuanCUADRADO);
	    Player CamiloVARGAS = Inserts.InsertPlayer(InstanceList, "Camilo VARGAS", 12, 25);
	    Links.LinkTeamAndPlayer(Colombia, CamiloVARGAS);
	    Player FredyGUARIN = Inserts.InsertPlayer(InstanceList, "Fredy GUARIN", 13, 28);
	    Links.LinkTeamAndPlayer(Colombia, FredyGUARIN);
	    Player VíctorIBARBO = Inserts.InsertPlayer(InstanceList, "Víctor IBARBO", 14, 24);
	    Links.LinkTeamAndPlayer(Colombia, VíctorIBARBO);
	    Player AlexanderMEJÍA = Inserts.InsertPlayer(InstanceList, "Alexander MEJÍA", 15, 26);
	    Links.LinkTeamAndPlayer(Colombia, AlexanderMEJÍA);
	    Player EderBALANTA = Inserts.InsertPlayer(InstanceList, "Eder BALANTA", 16, 21);
	    Links.LinkTeamAndPlayer(Colombia, EderBALANTA);
	    Player CarlosBacca = Inserts.InsertPlayer(InstanceList, "Carlos Bacca", 17, 28);
	    Links.LinkTeamAndPlayer(Colombia, CarlosBacca);
	    Player JuanZUNIGA = Inserts.InsertPlayer(InstanceList, "Juan ZUNIGA", 18, 27);
	    Links.LinkTeamAndPlayer(Colombia, JuanZUNIGA);
	    Player AdriánRamos = Inserts.InsertPlayer(InstanceList, "Adrián Ramos", 19, 28);
	    Links.LinkTeamAndPlayer(Colombia, AdriánRamos);
	    Player JuanQUINTERO = Inserts.InsertPlayer(InstanceList, "Juan QUINTERO", 20, 21);
	    Links.LinkTeamAndPlayer(Colombia, JuanQUINTERO);
	    Player JacksonMARTINEZ = Inserts.InsertPlayer(InstanceList, "Jackson MARTINEZ",21, 28);
	    Links.LinkTeamAndPlayer(Colombia, JacksonMARTINEZ);
	    Player FarydMONDRAGON = Inserts.InsertPlayer(InstanceList, "Faryd MONDRAGON", 22, 43);
	    Links.LinkTeamAndPlayer(Colombia, FarydMONDRAGON);
	    Player CarlosVALDES = Inserts.InsertPlayer(InstanceList, "Carlos VALDES", 23, 29);
	    Links.LinkTeamAndPlayer(Colombia, CarlosVALDES);

	    Team France = Inserts.InsertTeam(InstanceList, "France", "DESCHAMPS Didier", 7, 3, 1, 1, 5);
	    Player HugoLLORIS = Inserts.InsertPlayer(InstanceList, "Hugo LLORIS", 1, 28);
	    Links.LinkTeamAndPlayer(France, HugoLLORIS);
	    Player MathieuDEBUCHY = Inserts.InsertPlayer(InstanceList, "Mathieu DEBUCHY", 2, 29);
	    Links.LinkTeamAndPlayer(France, MathieuDEBUCHY);
	    Player PatriceEVRA = Inserts.InsertPlayer(InstanceList, "Patrice EVRA", 3, 33);
	    Links.LinkTeamAndPlayer(France, PatriceEVRA);
	    Player RaphaëlVARANE = Inserts.InsertPlayer(InstanceList, "Raphaël VARANE", 4, 21);
	    Links.LinkTeamAndPlayer(France, RaphaëlVARANE);
	    Player MamadouSAKHO = Inserts.InsertPlayer(InstanceList, "Mamadou SAKHO", 5, 24);
	    Links.LinkTeamAndPlayer(France, MamadouSAKHO);
	    Player YohanCabaye = Inserts.InsertPlayer(InstanceList, "Yohan Cabaye", 6, 28);
	    Links.LinkTeamAndPlayer(France, YohanCabaye);
	    Player RémyCABELLA = Inserts.InsertPlayer(InstanceList, "Rémy CABELLA", 7, 24);
	    Links.LinkTeamAndPlayer(France, RémyCABELLA);
	    Player MathieuValbuena = Inserts.InsertPlayer(InstanceList, "Mathieu Valbuena", 8, 30);
	    Links.LinkTeamAndPlayer(France, MathieuValbuena);
	    Player OlivierGiroud = Inserts.InsertPlayer(InstanceList, "Olivier Giroud", 9, 28);
	    Links.LinkTeamAndPlayer(France, OlivierGiroud);
	    Player KarimBenzema = Inserts.InsertPlayer(InstanceList, "Karim Benzema", 10, 27);
	    Links.LinkTeamAndPlayer(France, KarimBenzema);
	    Player AntoineGriezmann = Inserts.InsertPlayer(InstanceList, "Antoine Griezmann", 11, 23);
	    Links.LinkTeamAndPlayer(France, AntoineGriezmann);
	    Player RioMAVUBA = Inserts.InsertPlayer(InstanceList, "Rio MAVUBA", 12, 30);
	    Links.LinkTeamAndPlayer(France, RioMAVUBA);
	    Player EliaquimMANGALA = Inserts.InsertPlayer(InstanceList, "Eliaquim MANGALA", 13, 23);
	    Links.LinkTeamAndPlayer(France, EliaquimMANGALA);
	    Player BlaiseMatuidi = Inserts.InsertPlayer(InstanceList, "Blaise Matuidi", 14, 27);
	    Links.LinkTeamAndPlayer(France, BlaiseMatuidi);
	    Player BacarySAGNA = Inserts.InsertPlayer(InstanceList, "Bacary SAGNA", 15, 31);
	    Links.LinkTeamAndPlayer(France, BacarySAGNA);
	    Player StéphaneRUFFIER = Inserts.InsertPlayer(InstanceList, "Stéphane RUFFIER", 16, 28);
	    Links.LinkTeamAndPlayer(France, StéphaneRUFFIER);
	    Player LucasDIGNE = Inserts.InsertPlayer(InstanceList, "Lucas DIGNE", 17, 21);
	    Links.LinkTeamAndPlayer(France, LucasDIGNE);
	    Player MoussaSISSOKO = Inserts.InsertPlayer(InstanceList, "Moussa SISSOKO", 18, 25);
	    Links.LinkTeamAndPlayer(France, MoussaSISSOKO);
	    Player PaulPogba = Inserts.InsertPlayer(InstanceList, "Paul Pogba", 19, 22);
	    Links.LinkTeamAndPlayer(France, PaulPogba);
	    Player LoïcRÉMY = Inserts.InsertPlayer(InstanceList, "Loïc RÉMY", 20, 27);
	    Links.LinkTeamAndPlayer(France, LoïcRÉMY);
	    Player LaurentKoscielny = Inserts.InsertPlayer(InstanceList, "Laurent Koscielny",21, 29);
	    Links.LinkTeamAndPlayer(France, LaurentKoscielny);
	    Player MorganSCHNEIDERLIN = Inserts.InsertPlayer(InstanceList, "Morgan SCHNEIDERLIN", 22, 25);
	    Links.LinkTeamAndPlayer(France, MorganSCHNEIDERLIN);
	    Player MickaelLANDREAU = Inserts.InsertPlayer(InstanceList, "Mickael LANDREAU", 23, 35);
	    Links.LinkTeamAndPlayer(France, MickaelLANDREAU);

	    Team CostaRica = Inserts.InsertTeam(InstanceList, "Costa Rica", "PINTO Jorge Luis", 7, 3, 1, 1, 5);
	    Player KeylorNAVAS = Inserts.InsertPlayer(InstanceList, "Keylor NAVAS", 1, 28);
	    Links.LinkTeamAndPlayer(CostaRica, KeylorNAVAS);
	    Player JohnnyACOSTA = Inserts.InsertPlayer(InstanceList, "Johnny ACOSTA", 2, 31);
	    Links.LinkTeamAndPlayer(CostaRica, JohnnyACOSTA);
	    Player GiancarloGONZALEZ = Inserts.InsertPlayer(InstanceList, "Giancarlo GONZALEZ", 3, 26);
	    Links.LinkTeamAndPlayer(CostaRica, GiancarloGONZALEZ);
	    Player MichaelUMANA = Inserts.InsertPlayer(InstanceList, "Michael UMANA", 4, 32);
	    Links.LinkTeamAndPlayer(CostaRica, MichaelUMANA);
	    Player CelsoBORGES = Inserts.InsertPlayer(InstanceList, "Celso BORGES", 5, 26);
	    Links.LinkTeamAndPlayer(CostaRica, CelsoBORGES);
	    Player ÓscarDUARTE = Inserts.InsertPlayer(InstanceList, "Óscar DUARTE", 6, 25);
	    Links.LinkTeamAndPlayer(CostaRica, ÓscarDUARTE);
	    Player ChristianBOLANOS = Inserts.InsertPlayer(InstanceList, "Christian BOLANOS", 7, 30);
	    Links.LinkTeamAndPlayer(CostaRica, ChristianBOLANOS);
	    Player DaveMYRIE = Inserts.InsertPlayer(InstanceList, "Dave MYRIE", 8, 26);
	    Links.LinkTeamAndPlayer(CostaRica, DaveMYRIE);
	    Player JoelCAMPBELL = Inserts.InsertPlayer(InstanceList, "Joel CAMPBELL", 9, 22);
	    Links.LinkTeamAndPlayer(CostaRica, JoelCAMPBELL);
	    Player BryanRUIZ = Inserts.InsertPlayer(InstanceList, "Bryan RUIZ", 10, 29);
	    Links.LinkTeamAndPlayer(CostaRica, BryanRUIZ);
	    Player MichaelBARRANTES = Inserts.InsertPlayer(InstanceList, "Michael BARRANTES", 11, 31);
	    Links.LinkTeamAndPlayer(CostaRica, MichaelBARRANTES);
	    Player WaylonFRANCIS = Inserts.InsertPlayer(InstanceList, "Waylon FRANCIS", 12, 24);
	    Links.LinkTeamAndPlayer(CostaRica, WaylonFRANCIS);
	    Player EstebanGranados = Inserts.InsertPlayer(InstanceList, "Esteban Granados", 13, 29);
	    Links.LinkTeamAndPlayer(CostaRica, EstebanGranados);
	    Player RandallBRENES = Inserts.InsertPlayer(InstanceList, "Randall BRENES", 14, 31);
	    Links.LinkTeamAndPlayer(CostaRica, RandallBRENES);
	    Player JuniorDÍAZ = Inserts.InsertPlayer(InstanceList, "Junior DÍAZ", 15, 31);
	    Links.LinkTeamAndPlayer(CostaRica, JuniorDÍAZ);
	    Player CristianGAMBOA = Inserts.InsertPlayer(InstanceList, "Cristian GAMBOA", 16, 25);
	    Links.LinkTeamAndPlayer(CostaRica, CristianGAMBOA);
	    Player YeltsinTEJEDA = Inserts.InsertPlayer(InstanceList, "Yeltsin TEJEDA", 17, 22);
	    Links.LinkTeamAndPlayer(CostaRica, YeltsinTEJEDA);
	    Player PatrickPEMBERTON = Inserts.InsertPlayer(InstanceList, "Patrick PEMBERTON", 18, 32);
	    Links.LinkTeamAndPlayer(CostaRica, PatrickPEMBERTON);
	    Player RoyMILLER = Inserts.InsertPlayer(InstanceList, "Roy MILLER", 19, 30);
	    Links.LinkTeamAndPlayer(CostaRica, RoyMILLER);
	    Player DiegoCalvo = Inserts.InsertPlayer(InstanceList, "Diego Calvo", 20, 23);
	    Links.LinkTeamAndPlayer(CostaRica, DiegoCalvo);
	    Player MarcosURENA = Inserts.InsertPlayer(InstanceList, "Marcos URENA",21, 24);
	    Links.LinkTeamAndPlayer(CostaRica, MarcosURENA);
	    Player JoseCUBERO = Inserts.InsertPlayer(InstanceList, "Jose CUBERO", 22, 27);
	    Links.LinkTeamAndPlayer(CostaRica, JoseCUBERO);
	    Player DanielCAMBRONERO = Inserts.InsertPlayer(InstanceList, "Daniel CAMBRONERO", 23, 28);
	    Links.LinkTeamAndPlayer(CostaRica, DanielCAMBRONERO);


	    Team Belgium = Inserts.InsertTeam(InstanceList, "Belgium", "WILMOTS Marc", 9, 4, 0, 1, 5);
	    Player ThibautCOURTOIS = Inserts.InsertPlayer(InstanceList, "Thibaut COURTOIS", 1, 22);
	    Links.LinkTeamAndPlayer(Belgium, ThibautCOURTOIS);
	    Player TobyALDERWEIRELD = Inserts.InsertPlayer(InstanceList, "Toby ALDERWEIRELD", 2, 23);
	    Links.LinkTeamAndPlayer(Belgium, TobyALDERWEIRELD);
	    Player ThomasVERMAELEN = Inserts.InsertPlayer(InstanceList, "Thomas VERMAELEN", 3, 29);
	    Links.LinkTeamAndPlayer(Belgium, ThomasVERMAELEN);
	    Player VincentKOMPANY = Inserts.InsertPlayer(InstanceList, "Vincent KOMPANY", 4, 28);
	    Links.LinkTeamAndPlayer(Belgium, VincentKOMPANY);
	    Player JanVERTONGHEN = Inserts.InsertPlayer(InstanceList, "Jan VERTONGHEN", 5, 27);
	    Links.LinkTeamAndPlayer(Belgium, JanVERTONGHEN);
	    Player AxelWITSEL = Inserts.InsertPlayer(InstanceList, "Axel WITSEL", 6, 25);
	    Links.LinkTeamAndPlayer(Belgium, AxelWITSEL);
	    Player KevinDEBRUYNE = Inserts.InsertPlayer(InstanceList, "Kevin DE BRUYNE", 7, 23);
	    Links.LinkTeamAndPlayer(Belgium, KevinDEBRUYNE);
	    Player MarouaneFELLAINI = Inserts.InsertPlayer(InstanceList, "Marouane FELLAINI", 8, 27);
	    Links.LinkTeamAndPlayer(Belgium, MarouaneFELLAINI);
	    Player RomeluLUKAKU = Inserts.InsertPlayer(InstanceList, "Romelu LUKAKU", 9, 21);
	    Links.LinkTeamAndPlayer(Belgium, RomeluLUKAKU);
	    Player EdenHAZARD = Inserts.InsertPlayer(InstanceList, "Eden HAZARD", 10, 23);
	    Links.LinkTeamAndPlayer(Belgium, EdenHAZARD);
	    Player KevinMIRALLAS = Inserts.InsertPlayer(InstanceList, "Kevin MIRALLAS", 11, 27);
	    Links.LinkTeamAndPlayer(Belgium, KevinMIRALLAS);
	    Player SimonMIGNOLET = Inserts.InsertPlayer(InstanceList, "Simon MIGNOLET", 12, 26);
	    Links.LinkTeamAndPlayer(Belgium, SimonMIGNOLET);
	    Player SammyBOSSUT = Inserts.InsertPlayer(InstanceList, "Sammy BOSSUT", 13, 29);
	    Links.LinkTeamAndPlayer(Belgium, SammyBOSSUT);
	    Player DriesMERTENS = Inserts.InsertPlayer(InstanceList, "Dries MERTENS", 14, 27);
	    Links.LinkTeamAndPlayer(Belgium, DriesMERTENS);
	    Player DanielVANBUYTEN = Inserts.InsertPlayer(InstanceList, "Daniel VAN BUYTEN", 15, 36);
	    Links.LinkTeamAndPlayer(Belgium, DanielVANBUYTEN);
	    Player StevenDEFOUR = Inserts.InsertPlayer(InstanceList, "Steven DEFOUR", 16, 26);
	    Links.LinkTeamAndPlayer(Belgium, StevenDEFOUR);
	    Player DivockORIGI = Inserts.InsertPlayer(InstanceList, "Divock ORIGI", 17, 19);
	    Links.LinkTeamAndPlayer(Belgium, DivockORIGI);
	    Player NicolasLOMBAERTS = Inserts.InsertPlayer(InstanceList, "Nicolas LOMBAERTS", 18, 29);
	    Links.LinkTeamAndPlayer(Belgium, NicolasLOMBAERTS);
	    Player MoussaDEMBELE = Inserts.InsertPlayer(InstanceList, "Moussa DEMBELE", 19, 27);
	    Links.LinkTeamAndPlayer(Belgium, MoussaDEMBELE);
	    Player AdnanJANUZAJ = Inserts.InsertPlayer(InstanceList, "Adnan JANUZAJ", 20, 19);
	    Links.LinkTeamAndPlayer(Belgium, AdnanJANUZAJ);
	    Player AnthonyVANDENBORRE = Inserts.InsertPlayer(InstanceList, "Anthony VANDEN BORRE",21, 27);
	    Links.LinkTeamAndPlayer(Belgium, AnthonyVANDENBORRE);
	    Player NacerChadli = Inserts.InsertPlayer(InstanceList, "Nacer Chadli", 22, 25);
	    Links.LinkTeamAndPlayer(Belgium, NacerChadli);
	    Player LaurentCIMAN = Inserts.InsertPlayer(InstanceList, "Laurent CIMAN", 23, 29);
	    Links.LinkTeamAndPlayer(Belgium, LaurentCIMAN);
	    
	    
	    Team Chile = Inserts.InsertTeam(InstanceList, "Chile", "Jorge SAMPAOLI", 6, 2, 0, 2, 9);
	    Team Uruguay = Inserts.InsertTeam(InstanceList, "Uruguay", "TABAREZ Oscar", 6, 2, 0, 2, 9);
	    Team Nigeria = Inserts.InsertTeam(InstanceList, "Nigeria", "KESHI Stephen", 4, 1, 1, 2, 9);
	    Team Algeria = Inserts.InsertTeam(InstanceList, "Algeria", "Vahid HALILHODZIC", 4, 1, 1, 2, 9);
	    Team Mexico = Inserts.InsertTeam(InstanceList, "Mexico", "Miguel HERRERA", 7, 2, 1, 1, 9);
	    Team Greece = Inserts.InsertTeam(InstanceList, "Greece", "SANTOS Fernando", 4, 1, 1, 2, 9);
	    Team Switzerland = Inserts.InsertTeam(InstanceList, "Switzerland", "HITZFELD Ottmar", 6, 2, 0, 2, 9);
	    Team USA = Inserts.InsertTeam(InstanceList, "USA", "KLINSMANN Juergen", 4, 1, 1, 2, 9);
	    
	    Team Croatia = Inserts.InsertTeam(InstanceList, "Croatia", "KOVAC Niko", 3, 1, 0, 2, 17);
	    Team Cameroon = Inserts.InsertTeam(InstanceList, "Cameroon", "FINKE Volker", 0, 0, 0, 3, 17);
	    Team Spain = Inserts.InsertTeam(InstanceList, "Spain", "DEL BOSQUE Vicente", 3, 1, 0, 2, 17);
	    Team Australia = Inserts.InsertTeam(InstanceList, "Australia", "Ange POSTECOGLOU", 0, 0, 0, 3, 17);
	    Team CôtedIvoire = Inserts.InsertTeam(InstanceList, "Côte d'Ivoire", "LAMOUCHI Sabri", 3, 1, 0, 2, 17);
	    Team Japan = Inserts.InsertTeam(InstanceList, "Japan", "ZACCHERONI Alberto", 1, 0, 1, 2, 17);
	    Team Italy = Inserts.InsertTeam(InstanceList, "Italy", "PRANDELLI Cesare", 3, 1, 0, 2, 17);
	    Team England = Inserts.InsertTeam(InstanceList, "England", "HODGSON Roy", 1, 0, 1, 2, 17);
	    Team Ecuador = Inserts.InsertTeam(InstanceList, "Ecuador", "RUEDA Reinaldo", 4, 1, 1, 1, 17);
	    Team Honduras = Inserts.InsertTeam(InstanceList, "Honduras", "Luis FERNANDO SUÁREZ", 0, 0, 0, 3, 17);
	    Team BosniaandHerzegovina = Inserts.InsertTeam(InstanceList, "Bosnia and Herzegovina", "SUSIC Safet", 3, 1, 0, 2, 17);
	    Team Iran = Inserts.InsertTeam(InstanceList, "Iran", "Carlos QUEIRÓS", 0, 0, 1, 2, 17);
	    Team Portugal = Inserts.InsertTeam(InstanceList, "Portugal", "PAULO BENTO", 4, 1, 1, 1, 17);
	    Team Ghana = Inserts.InsertTeam(InstanceList, "Ghana", "APPIAH James", 1, 0, 1, 2, 17);
	    Team Russia = Inserts.InsertTeam(InstanceList, "Russia", "CAPELLO Fabio", 0, 0, 2, 1, 17);
	    Team KoreaRepublic = Inserts.InsertTeam(InstanceList, "Korea Republic", "HONG Myungbo", 1, 0, 1, 2, 17);
	    
	    Schedule Germanyfinal = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Argentinafinal = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Germanyfinal, Germany);
	    Links.LinkScheduleAndTeam(Argentinafinal, Argentina);
	    Event eventfinal = Inserts.InsertEvent(InstanceList, "1:0", "RIO DE JANEIRO", "Nicola RIZZOLI", "Final", "2014-07-13", "16:00");
	    Links.LinkScheduleAndEvent(Germanyfinal, eventfinal);
	    Links.LinkScheduleAndEvent(Argentinafinal, eventfinal);
	    
	    Schedule Brazilforthird = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Netherlandsforthird = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Brazilforthird, Brazil);
	    Links.LinkScheduleAndTeam(Netherlandsforthird, Netherlands);
	    Event eventforthird = Inserts.InsertEvent(InstanceList, "0:3", "BRASILIA", "Djamel HAIMOUDI", "Play-off for third place", "2014-07-12", "17:00");
	    Links.LinkScheduleAndEvent(Brazilforthird, eventforthird);
	    Links.LinkScheduleAndEvent(Netherlandsforthird, eventforthird);
	    
	    Schedule Netherlandssemi = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Argentinasemi = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Netherlandssemi, Netherlands);
	    Links.LinkScheduleAndTeam(Argentinasemi, Argentina);
	    Event eventsemi1 = Inserts.InsertEvent(InstanceList, "2:4", "SAO PAULO", "Cüneyt ÇAKIR", "Semi-finals", "2014-07-09", "17:00");
	    Links.LinkScheduleAndEvent(Netherlandssemi, eventsemi1);
	    Links.LinkScheduleAndEvent(Argentinasemi, eventsemi1);

	    Schedule Brazilsemi = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Germanysemi = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Brazilsemi, Brazil);
	    Links.LinkScheduleAndTeam(Germanysemi, Germany);
	    Event eventsemi2 = Inserts.InsertEvent(InstanceList, "1:7", "BELO HORIZONTE", "Marco RODRIGUEZ", "Semi-finals", "2014-07-08", "17:00");
	    Links.LinkScheduleAndEvent(Brazilsemi, eventsemi2);
	    Links.LinkScheduleAndEvent(Germanysemi, eventsemi2);
	    
	    Schedule Argentinaquarter = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Belgiumquarter = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Argentinaquarter, Argentina);
	    Links.LinkScheduleAndTeam(Belgiumquarter, Belgium);
	    Event eventquarter1 = Inserts.InsertEvent(InstanceList, "1:0", "BRASILIA", "Nicola RIZZOLI", "Quarter-finals", "2014-07-05", "13:00");
	    Links.LinkScheduleAndEvent(Argentinaquarter, eventquarter1);
	    Links.LinkScheduleAndEvent(Belgiumquarter, eventquarter1);
	    
	    Schedule Netherlandsquarter = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule CostaRicaquarter = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Netherlandsquarter, Netherlands);
	    Links.LinkScheduleAndTeam(CostaRicaquarter, CostaRica);
	    Event eventquarter2 = Inserts.InsertEvent(InstanceList, "4:3", "SALVADOR", "Ravshan IRMATOV", "Quarter-finals", "2014-07-05", "17:00");
	    Links.LinkScheduleAndEvent(Netherlandsquarter, eventquarter2);
	    Links.LinkScheduleAndEvent(CostaRicaquarter, eventquarter2);
	    
	    Schedule Francequarter = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Germanyquarter = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Francequarter, France);
	    Links.LinkScheduleAndTeam(Germanyquarter, Germany);
	    Event eventquarter3 = Inserts.InsertEvent(InstanceList, "0:1", "RIO DE JANEIRO", "Néstor PITANA", "Quarter-finals", "2014-07-04", "13:00");
	    Links.LinkScheduleAndEvent(Francequarter, eventquarter3);
	    Links.LinkScheduleAndEvent(Germanyquarter, eventquarter3);
	    
	    Schedule Brazilquarter = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Colombiaquarter = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Brazilquarter, Brazil);
	    Links.LinkScheduleAndTeam(Colombiaquarter, Colombia);
	    Event eventquarter4 = Inserts.InsertEvent(InstanceList, "2:1", "FORTALEZA", "Carlos VELASCO CARBALLO", "Quarter-finals", "2014-07-04", "17:00");
	    Links.LinkScheduleAndEvent(Brazilquarter, eventquarter4);
	    Links.LinkScheduleAndEvent(Colombiaquarter, eventquarter4);
	    
	    Schedule Brazilroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Chileroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Brazilroundof16, Brazil);
	    Links.LinkScheduleAndTeam(Chileroundof16, Chile);
	    Event eventroundof161 = Inserts.InsertEvent(InstanceList, "4:3", "BELO HORIZONTE", "Howard WEBB", "Round of 16", "2014-06-28", "13:00");
	    Links.LinkScheduleAndEvent(Brazilroundof16, eventroundof161);
	    Links.LinkScheduleAndEvent(Chileroundof16, eventroundof161);
	    
	    Schedule Colombiaroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Uruguayroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Colombiaroundof16, Colombia);
	    Links.LinkScheduleAndTeam(Uruguayroundof16, Uruguay);
	    Event eventroundof162 = Inserts.InsertEvent(InstanceList, "2:0", "RIO DE JANEIRO", "Björn KUIPERS", "Round of 16", "2014-06-28", "17:00");
	    Links.LinkScheduleAndEvent(Colombiaroundof16, eventroundof162);
	    Links.LinkScheduleAndEvent(Uruguayroundof16, eventroundof162);
	    
	    Schedule Netherlandsroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Mexicoroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Netherlandsroundof16, Netherlands);
	    Links.LinkScheduleAndTeam(Mexicoroundof16, Mexico);
	    Event eventroundof163 = Inserts.InsertEvent(InstanceList, "2:1", "FORTALEZA", "Pedro PROENCA", "Round of 16", "2014-06-29", "13:00");
	    Links.LinkScheduleAndEvent(Netherlandsroundof16, eventroundof163);
	    Links.LinkScheduleAndEvent(Mexicoroundof16, eventroundof163);
	    
	    Schedule CostaRicaroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Greeceroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(CostaRicaroundof16, CostaRica);
	    Links.LinkScheduleAndTeam(Greeceroundof16, Greece);
	    Event eventroundof164 = Inserts.InsertEvent(InstanceList, "6:4", "RECIFE", "Ben WILLIAMS", "Round of 16", "2014-06-29", "17:00");
	    Links.LinkScheduleAndEvent(CostaRicaroundof16, eventroundof164);
	    Links.LinkScheduleAndEvent(Greeceroundof16, eventroundof164);
	    
	    Schedule Franceroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Nigeriaroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Franceroundof16, France);
	    Links.LinkScheduleAndTeam(Nigeriaroundof16, Nigeria);
	    Event eventroundof165 = Inserts.InsertEvent(InstanceList, "2:0", "BRASILIA", "Mark GEIGER", "Round of 16", "2014-06-30", "13:00");
	    Links.LinkScheduleAndEvent(Franceroundof16, eventroundof165);
	    Links.LinkScheduleAndEvent(Nigeriaroundof16, eventroundof165);
	    
	    Schedule Germanyroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Algeriaroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Germanyroundof16, Germany);
	    Links.LinkScheduleAndTeam(Algeriaroundof16, Algeria);
	    Event eventroundof166 = Inserts.InsertEvent(InstanceList, "2:1", "PORTO ALEGRE", "Sandro RICCI", "Round of 16", "2014-06-30", "17:00");
	    Links.LinkScheduleAndEvent(Germanyroundof16, eventroundof166);
	    Links.LinkScheduleAndEvent(Algeriaroundof16, eventroundof166);
	    
	    Schedule Argentinaroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule Switzerlandroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Argentinaroundof16, Argentina);
	    Links.LinkScheduleAndTeam(Switzerlandroundof16, Switzerland);
	    Event eventroundof167 = Inserts.InsertEvent(InstanceList, "1:0", "SAO PAULO", "Jonas ERIKSSON", "Round of 16", "2014-07-01", "13:00");
	    Links.LinkScheduleAndEvent(Argentinaroundof16, eventroundof167);
	    Links.LinkScheduleAndEvent(Switzerlandroundof16, eventroundof167);
	    
	    Schedule Belgiumroundof16 = Inserts.InsertSchedule(InstanceList, "Home");
	    Schedule USAroundof16 = Inserts.InsertSchedule(InstanceList, "Away");
	    Links.LinkScheduleAndTeam(Belgiumroundof16, Belgium);
	    Links.LinkScheduleAndTeam(USAroundof16, USA);
	    Event eventroundof168 = Inserts.InsertEvent(InstanceList, "1:0", "SALVADOR", "Djamel HAIMOUDI", "Round of 16", "2014-07-01", "17:00");
	    Links.LinkScheduleAndEvent(Belgiumroundof16, eventroundof168);
	    Links.LinkScheduleAndEvent(USAroundof16, eventroundof168);
	    
	    //final
	    PlayerPerformance MarioGOETZEfinalperformence = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-13", 120, "Final", 1);
	    Links.LinkPlayerAndPerformance(MarioGOETZE, MarioGOETZEfinalperformence);
	    //play-off for third place
	    PlayerPerformance RobinVANPERSIEforthirdperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-12", 90, "Play-off for third place", 1);
	    Links.LinkPlayerAndPerformance(RobinVANPERSIE, RobinVANPERSIEforthirdperformance);
	    PlayerPerformance DaleyBLINDforthirdperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-12", 70, "Play-off for third place", 1);
	    Links.LinkPlayerAndPerformance(RobinVANPERSIE, DaleyBLINDforthirdperformance);
	    PlayerPerformance GeorginioWijnaldumforthirdperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-12", 90, "Play-off for third place", 1);
	    Links.LinkPlayerAndPerformance(GeorginioWijnaldum, GeorginioWijnaldumforthirdperformance);
	    //semi-finals between Netherlands and Argentina(平局)
	    //semi-finals between Brazil and Germany
	    PlayerPerformance OSCARsemiperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-08", 90, "Semi-finals", 1);
	    Links.LinkPlayerAndPerformance(OSCAR, OSCARsemiperformance);
	    PlayerPerformance ThomasMUELLERsemiperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-08", 90, "Semi-finals", 1);
	    Links.LinkPlayerAndPerformance(ThomasMUELLER, ThomasMUELLERsemiperformance);
	    PlayerPerformance MiroslavKLOSEsemiperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-08", 58, "Semi-finals", 1);
	    Links.LinkPlayerAndPerformance(MiroslavKLOSE, MiroslavKLOSEsemiperformance);
	    PlayerPerformance ToniKROOSsemiperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-08", 90, "Semi-finals", 2);
	    Links.LinkPlayerAndPerformance(ToniKROOS, ToniKROOSsemiperformance);
	    PlayerPerformance SamiKHEDIRAsemiperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-08", 76, "Semi-finals", 1);
	    Links.LinkPlayerAndPerformance(SamiKHEDIRA, SamiKHEDIRAsemiperformance);
	    PlayerPerformance AndreSCHUERRLEsemiperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-08", 32, "Semi-finals", 2);
	    Links.LinkPlayerAndPerformance(AndreSCHUERRLE, AndreSCHUERRLEsemiperformance);
	    //semi-finals between Argentina and Belgium
	    PlayerPerformance GonzaloHIGUAINquarterperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-05", 81, "Quarter-finals", 1);
	    Links.LinkPlayerAndPerformance(GonzaloHIGUAIN, GonzaloHIGUAINquarterperformance);
	    //semi-finals between France and Germany
	    PlayerPerformance MatsHUMMELSquarterperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-04", 90, "Quarter-finals", 1);
	    Links.LinkPlayerAndPerformance(MatsHUMMELS, MatsHUMMELSquarterperformance);
	    //semi-finals between Brazil and Colombia
	    PlayerPerformance THIAGOSILVAquarterperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-04", 90, "Quarter-finals", 1);
	    Links.LinkPlayerAndPerformance(THIAGOSILVA, THIAGOSILVAquarterperformance);
	    PlayerPerformance DAVIDLUIZquarterperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-04", 90, "Quarter-finals", 1);
	    Links.LinkPlayerAndPerformance(DAVIDLUIZ, DAVIDLUIZquarterperformance);
	    PlayerPerformance JamesRODRIGUEZquarterperformance = Inserts.InsertPlayerPerformance(InstanceList, "2014-07-04", 90, "Quarter-finals", 1);
	    Links.LinkPlayerAndPerformance(JamesRODRIGUEZ, JamesRODRIGUEZquarterperformance);

	    em.getTransaction().begin();
	    for(Object instance: InstanceList) em.persist(instance);
	    em.getTransaction().commit();
	    em.close();
	    factory.close();
	}
}